name: E-commerce API CI

# Trigger the workflow on push to any branch or pull requests
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  
# Jobs to run
jobs:
  test:
    name: Test FastAPI Application
    runs-on: ubuntu-latest
    
    # MySQL service container for testing
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: 1111
          MYSQL_DATABASE: ecom_db
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h localhost -u root -p1111"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      # Checkout repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Setup Python environment
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      # Initialize the database with schema
      - name: Initialize Database
        run: |
          mysql -h127.0.0.1 -uroot -p1111 ecom_db < schema.sql
          
      # Run tests
      - name: Run tests
        env:
          DB_HOST: 127.0.0.1
          DB_USER: root
          DB_PASSWORD: 1111
          DB_NAME: ecom_db
        run: |
          pytest -v --cov=./ tests/
          
  build:
    name: Build Docker Image
    runs-on: ubuntu-latest
    needs: test
    if: github.event_name == 'push' && github.ref == 'refs/heads/main' ||  github.event_name == 'pull_request'

    steps:
      # Checkout repository
      - name: Checkout code
        uses: actions/checkout@v3
        
      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      # Login to DockerHub
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}       
        
        
      # Build the Docker image
      - name: Build Docker image and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: natoeiei/project_ecom:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

  #deploy to DigitalOcean Droplet
  deploy:
    name: Deploy to DigitalOcean Droplet
    runs-on: ubuntu-latest
    needs: build  # รอให้ Build Docker Image เสร็จก่อน
    if: github.event_name == 'push' && github.ref == 'refs/heads/main' ||  github.event_name == 'pull_request'

    steps:
      - name: Setup SSH Key
        run: |
          echo ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQC4Haws7iBPT8L+zwN5Is1cJpATCasUm/SagUhWdK7pfTwOFrYXbG3Zrcmeer3Qxjv62phnWXQTUg8xDdPNZoCnyfb2LquJjyOa6Fg1uz1n5BESQcew1/GSzJxPe+sMqb/GMm0AAi07/fwDDwuvK3NPh8PnSTkia8iK/RTg0/qzQGBSKJlMbY3KtlrUehEye3O04XQWr8rMuh+TWVNX3fok7ubXkJUsHheNsS2OTOjuUrYDxLLcj/ffLMYTwDwKz29n3Olq2hol8y0ZWLGpVJxyku8V03fuAichX9MxlTVz6LQcPu3nWDbSRILzufr1ujCU37Vi/7I2CdNkswAb39HYOdns6ZQmyQTVDcvOKq85QGRUArj2dlFxXCaKxRkwQ9R8dw3+AtjhWdGYahEGJzdKLVoxwldgErzRnqhh6+pAD/9kKqHMdrRgZzuO8V+cgU3nptKlp5qsYAy4FV++x9L3WL5W+CP28tBGT3j0aOkKG/GCpJoeJD50dVDdX3jc7JoY50ncUKDLAil7+baDaS5aq2gQl99pcCXXpo7wRl4YHx0miOB6iLbAtW4CS1uybPGL2bdSFF5sUGqJcNN/r5h6CHJUoR0KoFM1Ws1Q2Y0PHioSgO23OiRv58rTSliMPhKR2ZhhfDj7/H0Q3jTvf06jlF1km+SK/sSTil9Q+enGgQ== thongtara.chaiwat@gmail.com > key.pem
          chmod 600 key.pem
        env:
          SSH_KEY: ${{ secrets.DO_SSH_KEY }}

      - name: Connect & Deploy
        run: |
          ssh -o StrictHostKeyChecking=no -i key.pem ${{ secrets.DROPLET_USER }}@${{ secrets.DROPLET_IP }} << 'EOF'
            cd /root || mkdir -p /root && cd /root
            rm -rf project_ecom
            git clone https://github.com/natoeiei/project_ecom.git
            cd project_ecom
            sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
            sudo chmod +x /usr/local/bin/docker-compose
            sudo apt update
            sudo apt install docker.io -y
            sudo systemctl start docker
            docker-compose pull
            docker-compose up -d
          EOF
        

